window.MHHorizonHubs = [
  {
    id: "gamehub",
    name: "Game Hub",
    category: "Games",
    status: "Live Node",
    state: "live",
    featured: true,
    logo: "gamehub_logo.png",
    description:
      "The live MH Horizon games destination for browser-play experiences, fast sessions, polished discovery, and direct access into the gaming branch.",
    tagline: "Play-first momentum with a dedicated live hub identity.",
    features: ["Live at gamehub.mhhorizons.com", "Playable experiences", "Fast session loops"],
    link: "https://gamehub.mhhorizons.com/",
    note: "Online now at gamehub.mhhorizons.com.",
  },
  {
    id: "informative-hub",
    name: "Informative Hub",
    category: "Knowledge",
    status: "Live Node",
    state: "live",
    featured: true,
    logo: "informativehub_logo.png",
    description:
      "The live knowledge destination for clear information delivery, contextual organization, and reference-ready reading inside the MH Horizon ecosystem.",
    tagline: "Clarity, context, and smart presentation in one online hub.",
    features: ["Live at informativehub.mhhorizons.com", "Insight-led content", "Reference layout"],
    link: "https://informativehub.mhhorizons.com/",
    note: "Online now at informativehub.mhhorizons.com.",
  },
  {
    id: "recipifyhub",
    name: "Recipify Hub",
    category: "Food",
    status: "Live Node",
    state: "live",
    featured: true,
    logo: "recipifyhub.png",
    description:
      "The live MH Horizon food destination for recipe discovery, meal ideas, and beautifully organized cooking inspiration.",
    tagline: "Taste-first browsing with a clean recipe gateway.",
    features: ["Live at recipify.mhhorizons.com", "Recipe collections", "Food inspiration"],
    link: "https://recipify.mhhorizons.com/",
    note: "Online now at recipify.mhhorizons.com.",
  },
  {
    id: "focusforge",
    name: "FocusForge",
    category: "Productivity",
    status: "Beta Node",
    state: "beta",
    featured: true,
    description:
      "A productivity world for focused work sessions, personal momentum, and calmer task structure.",
    tagline: "Built for focus, habit, and steady execution.",
    features: ["Focus sessions", "Task rhythm", "Productive flow"],
    link: "#",
    note: "This beta node is reserved for the FocusForge launch route.",
  },
  {
    id: "mh-tools",
    name: "MH Tools",
    category: "Utilities",
    status: "Live Node",
    state: "live",
    description:
      "A practical utility branch for quick workflows, creator tools, and task-friendly digital helpers.",
    tagline: "Function-forward experiences built for usefulness and speed.",
    features: ["Tool workflows", "Practical helpers", "Clean utility focus"],
    link: "#",
    note: "Direct launch routing for this node will appear here when the public MH Tools link goes live.",
  },
  {
    id: "pythonlab",
    name: "PythonLab",
    category: "Coding",
    status: "Live Node",
    state: "live",
    logo: "pythonlab.png",
    description:
      "The live MH Horizon coding destination for writing, testing, and exploring Python ideas in a focused browser workspace.",
    tagline: "A compact Python lab inside the wider horizon.",
    features: ["Live at pythonlab.mhhorizons.com", "Python workspace", "Code experiments"],
    link: "https://pythonlab.mhhorizons.com/",
    note: "Online now at pythonlab.mhhorizons.com.",
  },
  {
    id: "gh-quizz",
    name: "GH Quizz",
    category: "Learning",
    status: "Live Node",
    state: "live",
    description:
      "A quiz-centered branch designed for challenge loops, score-driven curiosity, and shareable fun.",
    tagline: "Quick-thinking competition with a clean challenge loop.",
    features: ["Quiz formats", "Competitive tone", "Progression hooks"],
    link: "#",
    note: "Direct launch routing for this node will appear here when the public GH Quizz link goes live.",
  },
  {
    id: "fictionalis-hub",
    name: "Fictionalis Hub",
    category: "Stories",
    status: "Coming Soon",
    state: "coming-soon",
    description:
      "A narrative-led hub prepared for fiction, atmosphere, and story-driven digital experiences.",
    tagline: "A story portal waiting for its official world to open.",
    features: ["Narrative preview", "Atmospheric writing", "Future content stage"],
    link: "siteunderconstruction/index.html",
    note: "Currently routed to the construction holding page until Fictionalis Hub opens.",
  },
  {
    id: "3d-modination-hub",
    name: "3D Modination Hub",
    category: "3D",
    status: "Experimental",
    state: "experimental",
    description:
      "A future-facing immersive node prepared for 3D creativity, motion, and experimental digital worlds.",
    tagline: "A reserved portal for the next dimensional release.",
    features: ["3D identity", "Motion experiments", "Immersive concepts"],
    link: "siteunderconstruction/index.html",
    note: "Currently routed to the construction holding page until 3D Modination Hub opens.",
  },
  {
    id: "nexus-chat",
    name: "Nexus Chat",
    category: "Communication",
    status: "Maintenance Bay",
    state: "maintenance",
    description:
      "A communication-focused hub reserved here as a dark launch pad while maintenance wraps up.",
    tagline: "A quiet docking point ready for its reconnect moment.",
    features: ["Maintenance mode", "Black-slot presentation", "Future reactivation"],
    link: "siteunderconstruction/maintenance.html",
    note: "Currently routed to the maintenance holding page while Nexus Chat is serviced.",
  },
];
