window.MHHorizonHubs = [
  {
    id: "gamehub",
    name: "Game Hub",
    category: "Games",
    status: "Live Node",
    state: "live",
    featured: true,
    logo: "gamehub_logo.png",
    description:
      "The live MH Horizon games destination for browser-play experiences, fast sessions, polished discovery, and direct access into the gaming branch.",
    tagline: "Play-first momentum with a dedicated live hub identity.",
    features: ["Live at gamehub.mhhorizons.com", "Playable experiences", "Fast session loops"],
    link: "https://gamehub.mhhorizons.com/",
    note: "Online now at gamehub.mhhorizons.com.",
  },
  {
    id: "informative-hub",
    name: "Informative Hub",
    category: "Knowledge",
    status: "Live Node",
    state: "live",
    featured: true,
    logo: "informativehub_logo.png",
    description:
      "The live knowledge destination for clear information delivery, contextual organization, and reference-ready reading inside the MH Horizon ecosystem.",
    tagline: "Clarity, context, and smart presentation in one online hub.",
    features: ["Live at informativehub.mhhorizons.com", "Insight-led content", "Reference layout"],
    link: "https://informativehub.mhhorizons.com/",
    note: "Online now at informativehub.mhhorizons.com.",
  },
  {
    id: "recipifyhub",
    name: "Recipify Hub",
    category: "Food",
    status: "Live Node",
    state: "live",
    featured: true,
    logo: "recipifyhub.png",
    description:
      "The live MH Horizon food destination for recipe discovery, meal ideas, and beautifully organized cooking inspiration.",
    tagline: "Taste-first browsing with a clean recipe gateway.",
    features: ["Live at recipify.mhhorizons.com", "Recipe collections", "Food inspiration"],
    link: "https://recipify.mhhorizons.com/",
    note: "Online now at recipify.mhhorizons.com.",
  },
  {
    id: "focusforge",
    name: "FocusForge",
    category: "Productivity",
    status: "Live Node",
    state: "live",
    featured: true,
    logo: "focus_forge_logo.png",
    description:
      "The live MH Horizon productivity destination for focused work sessions, personal momentum, and calmer task structure.",
    tagline: "Built for focus, habit, and steady execution.",
    features: ["Live at focusforge.mhhorizon.com", "Focus sessions", "Productive flow"],
    link: "https://focusforge.mhhorizon.com/",
    note: "Online now at focusforge.mhhorizon.com.",
  },
  {
    id: "mh-tools",
    name: "MH Tools",
    category: "Utilities",
    status: "Live Node",
    state: "live",
    logo: "tools.png",
    description:
      "The live MH Horizon utility destination for quick workflows, creator tools, media helpers, and task-friendly digital utilities.",
    tagline: "Function-forward tools built for usefulness, speed, and clean everyday workflows.",
    features: ["Live at tools.mhhorizons.com", "Tool workflows", "Media & link utilities"],
    link: "https://tools.mhhorizons.com/",
    note: "Online now at tools.mhhorizons.com.",
  },
  {
    id: "pythonlab",
    name: "PythonLab",
    category: "Coding",
    status: "Live Node",
    state: "live",
    logo: "pythonlab.png",
    description:
      "The live MH Horizon coding destination for writing, testing, and exploring Python ideas in a focused browser workspace.",
    tagline: "A compact Python lab inside the wider horizon.",
    features: ["Live at pythonlab.mhhorizons.com", "Python workspace", "Code experiments"],
    link: "https://pythonlab.mhhorizons.com/",
    note: "Online now at pythonlab.mhhorizons.com.",
  },
  {
    id: "quizora",
    name: "Quizora",
    category: "Learning",
    status: "Live Node",
    state: "live",
    logo: "quizora.png",
    description:
      "The live MH Horizon quiz destination for hosting, playing, and tracking quiz rooms with leaderboard-driven learning loops.",
    tagline: "Live rooms, scoreboards, and smarter quiz hosting in one learning hub.",
    features: ["Live at quizora.mhhorizons.com", "Live quiz rooms", "Leaderboards & analytics"],
    link: "https://quizora.mhhorizons.com/",
    note: "Online now at quizora.mhhorizons.com.",
  },
  {
    id: "nexus-chat",
    name: "Nexus Chat",
    category: "Communication",
    status: "Live Node",
    state: "live",
    logo: "nexus_logo.png",
    description:
      "The live MH Horizon communication destination for chat-first conversations, social connection, and real-time community presence.",
    tagline: "A live communication hub for fast conversations and connected rooms.",
    features: ["Live at nexus.mhhorizons.com", "Chat rooms", "Real-time communication"],
    link: "https://nexus.mhhorizons.com/",
    note: "Online now at nexus.mhhorizons.com.",
  },
  {
    id: "fictionalis-hub",
    name: "Fictionalis Hub",
    category: "Maintenance",
    status: "Maintenance Bay",
    state: "maintenance",
    description:
      "A narrative-led hub currently held in maintenance while its fiction, atmosphere, and story-driven experience is prepared.",
    tagline: "A story portal being serviced before its official world opens.",
    features: ["Maintenance mode", "Story hub preparation", "Future content stage"],
    link: "siteunderconstruction/maintenance.html",
    note: "Currently routed to the maintenance holding page while Fictionalis Hub is serviced.",
  },
  {
    id: "3d-modination-hub",
    name: "3D Modination Hub",
    category: "3D",
    status: "Experimental",
    state: "experimental",
    description:
      "A future-facing immersive node prepared for 3D creativity, motion, and experimental digital worlds.",
    tagline: "A reserved portal for the next dimensional release.",
    features: ["3D identity", "Motion experiments", "Immersive concepts"],
    link: "siteunderconstruction/index.html",
    note: "Currently routed to the construction holding page until 3D Modination Hub opens.",
  },
];
